version: "3.8"
services:
  dev-postgres:
    image: postgres:14.4-alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: some-dev
      POSTGRES_PASSWORD: some-dev
      POSTGRES_DB: some-dev
    restart: always
    networks:
      - dev-db
networks:
  dev-db: